// Generated by scripts/export_schemas.py from elp_api.models; do not edit.
// These types describe serialized API values and have no independent compatibility policy.

export interface ButtonControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  type: "button";
  default: string | number | boolean | null;
}

export interface CalloutBlock {
  title: string | null;
  type: "callout";
  source: string | null;
  text: string | null;
  tone: "info" | "success" | "warning" | "danger";
}

export interface ContentRevision {
  schema_version: 1;
  content_digest: string;
  source_git_commit: string | null;
}

export interface ControlOption {
  label: string;
  value: string | number | boolean;
}

export type ControlSpec = SliderControl | NumberControl | ToggleControl | SelectControl | SegmentedControl | ButtonControl;

export interface ControlsBlock {
  title: string | null;
  type: "controls";
}

export interface CourseSummary {
  id: string;
  title: string;
  description: string;
  order: number;
  tags: Array<string>;
  modules: Array<ModuleSummary>;
  revision: ContentRevision;
}

export interface DividerBlock {
  type: "divider";
}

export type LessonBlock = MarkdownBlock | PredictionBlock | ControlsBlock | MetricsBlock | PlotBlock | PlotGridBlock | TableBlock | CalloutBlock | WidgetBlock | DividerBlock;

export interface MarkdownBlock {
  title: string | null;
  type: "markdown";
  source: string | null;
  text: string | null;
}

export interface Metric {
  id: string;
  label: string;
  value: string | number | boolean | null;
  unit: string | null;
  detail: string | null;
  emphasis: "normal" | "primary" | "warning" | "danger";
}

export interface MetricsBlock {
  title: string | null;
  type: "metrics";
}

export interface ModuleDocument {
  course: CourseSummary;
  module: ModuleManifest;
  markdown_sources: Record<string, string>;
  default_parameters: Record<string, unknown>;
  module_revision: ContentRevision;
  platform_revision: PlatformRevision;
}

export interface ModuleManifest {
  schema_version: 1;
  id: string;
  number: number | null;
  title: string;
  summary: string;
  guiding_question: string;
  status: "draft" | "implemented" | "static";
  runtime: StaticRuntime | PythonRuntime;
  controls: Array<SliderControl | NumberControl | ToggleControl | SelectControl | SegmentedControl | ButtonControl>;
  blocks: Array<MarkdownBlock | PredictionBlock | ControlsBlock | MetricsBlock | PlotBlock | PlotGridBlock | TableBlock | CalloutBlock | WidgetBlock | DividerBlock>;
  tags: Array<string>;
}

export interface ModuleSummary {
  id: string;
  number: number | null;
  title: string;
  summary: string;
  status: string;
  interactive: boolean;
  revision: ContentRevision;
}

export interface NumberControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  default: number;
  minimum: number;
  maximum: number;
  step: number | null;
  type: "number";
}

export interface ParameterMapProps {
  x_control: string;
  y_control: string;
  x_label: string;
  y_label: string;
}

export interface PlatformRevision {
  platform_version: string;
  platform_git_commit: string | null;
  runtime_content_digest: string;
  runtime_kind: "python-in-process" | "static";
}

export interface PlotBlock {
  title: string | null;
  type: "plot";
  plot: string;
}

export interface PlotGridBlock {
  title: string | null;
  type: "plot_grid";
  plots: Array<string>;
}

export interface PlotSpec {
  data: Array<Record<string, unknown>>;
  layout: Record<string, unknown>;
  config: Record<string, unknown>;
  frames: Array<Record<string, unknown>>;
}

export interface PredictionBlock {
  title: string | null;
  type: "prediction";
  text: string;
  reveal: string | null;
}

export interface PythonRuntime {
  kind: "python";
  entrypoint: string;
  trust: "local-trusted";
  timeout_seconds: number | null;
}

export interface RunRequest {
  parameters: Record<string, unknown>;
  expected_content_digest: string;
}

export interface RunResult {
  parameters: Record<string, unknown>;
  metrics: Array<Metric>;
  plots: Record<string, PlotSpec>;
  tables: Record<string, TableSpec>;
  explanations: Record<string, string>;
  warnings: Array<string>;
  diagnostics: Record<string, unknown>;
  course_revision: ContentRevision;
  module_revision: ContentRevision;
  platform_revision: PlatformRevision;
}

export type RuntimeSpec = StaticRuntime | PythonRuntime;

export interface SegmentedControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  type: "segmented";
  default: string | number | boolean;
  options: Array<ControlOption>;
}

export interface SelectControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  type: "select";
  default: string | number | boolean;
  options: Array<ControlOption>;
}

export interface SliderControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  default: number;
  minimum: number;
  maximum: number;
  step: number | null;
  type: "slider";
}

export interface StaticRuntime {
  kind: "static";
  trust: "local-trusted";
}

export interface TableBlock {
  title: string | null;
  type: "table";
  table: string;
}

export interface TableSpec {
  columns: Array<string>;
  rows: Array<Record<string, unknown>>;
}

export interface ToggleControl {
  id: string;
  label: string;
  description: string | null;
  unit: string | null;
  visible_when: Record<string, string | number | boolean | null> | null;
  type: "toggle";
  default: boolean;
}

export interface WidgetBlock {
  title: string | null;
  type: "widget";
  widget: "parameter-map";
  props: ParameterMapProps;
}
